setGeneric("calculateEmission", function(object, ...) standardGeneric("calculateEmission"))
setGeneric("computeEmission", function(object, hmmOptions) standardGeneric("computeEmission"))
setGeneric("computeHmm", function(object, hmmOptions) standardGeneric("computeHmm"))
setGeneric("emissionPr", function(object) standardGeneric("emissionPr"))
setGeneric("emissionPr<-", function(object, value) standardGeneric("emissionPr<-"))
setGeneric("rangedData", function(object) standardGeneric("rangedData"))
setGeneric("rangedData<-", function(object, value) standardGeneric("rangedData<-"))
setGeneric("segmentData", function(object) standardGeneric("segmentData"))
setGeneric("segmentData<-", function(object, value) standardGeneric("segmentData<-"))
